-- Create course_lessons table for Payload CMS
-- This table is referenced by the CourseLessons collection

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create enum types
CREATE TYPE payload.enum_course_lessons_status AS ENUM ('draft', 'published');

-- Create the course_lessons table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.course_lessons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title varchar NOT NULL,
  slug varchar NOT NULL UNIQUE,
  description varchar,
  content jsonb,
  lesson_number numeric NOT NULL,
  estimated_duration numeric,
  published_at timestamp(3) with time zone,
  status payload.enum_course_lessons_status DEFAULT 'draft' NOT NULL,
  "order" numeric DEFAULT 0,
  language varchar DEFAULT 'en',
  course integer,
  quiz integer,
  featured_image integer,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.course_lessons ADD CONSTRAINT course_lessons_course_fk FOREIGN KEY (course) REFERENCES payload.courses(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
  -- If the courses table doesn't exist yet, we'll skip this constraint
  WHEN undefined_table THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.course_lessons ADD CONSTRAINT course_lessons_quiz_fk FOREIGN KEY (quiz) REFERENCES payload.course_quizzes(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.course_lessons ADD CONSTRAINT course_lessons_featured_image_fk FOREIGN KEY (featured_image) REFERENCES payload.media(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS course_lessons_course_idx ON payload.course_lessons USING btree (course);
CREATE INDEX IF NOT EXISTS course_lessons_quiz_idx ON payload.course_lessons USING btree (quiz);
CREATE INDEX IF NOT EXISTS course_lessons_featured_image_idx ON payload.course_lessons USING btree (featured_image);
CREATE INDEX IF NOT EXISTS course_lessons_updated_at_idx ON payload.course_lessons USING btree (updated_at);
CREATE INDEX IF NOT EXISTS course_lessons_created_at_idx ON payload.course_lessons USING btree (created_at);
