-- Create surveys table for Payload CMS
-- This table is for user assessment and feedback surveys

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create enum types
CREATE TYPE payload.enum_surveys_status AS ENUM ('draft', 'published');

-- Create the surveys table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.surveys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title varchar NOT NULL,
  slug varchar NOT NULL UNIQUE,
  description varchar,
  start_message jsonb,
  end_message jsonb,
  show_progress_bar boolean DEFAULT true,
  summary_content jsonb,
  status payload.enum_surveys_status DEFAULT 'draft' NOT NULL,
  published_at timestamp(3) with time zone,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Create the surveys_questions_rels table for the many-to-many relationship
CREATE TABLE IF NOT EXISTS payload.surveys_questions_rels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order" integer,
  parent_id integer NOT NULL,
  path varchar NOT NULL,
  survey_questions_id integer
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.surveys_questions_rels ADD CONSTRAINT surveys_questions_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES payload.surveys(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.surveys_questions_rels ADD CONSTRAINT surveys_questions_rels_survey_questions_fk FOREIGN KEY (survey_questions_id) REFERENCES payload.survey_questions(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
  -- If the survey_questions table doesn't exist yet, we'll skip this constraint
  WHEN undefined_table THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS surveys_updated_at_idx ON payload.surveys USING btree (updated_at);
CREATE INDEX IF NOT EXISTS surveys_created_at_idx ON payload.surveys USING btree (created_at);
CREATE INDEX IF NOT EXISTS surveys_questions_rels_order_idx ON payload.surveys_questions_rels USING btree ("order");
CREATE INDEX IF NOT EXISTS surveys_questions_rels_parent_idx ON payload.surveys_questions_rels USING btree (parent_id);
CREATE INDEX IF NOT EXISTS surveys_questions_rels_path_idx ON payload.surveys_questions_rels USING btree (path);
CREATE INDEX IF NOT EXISTS surveys_questions_rels_survey_questions_id_idx ON payload.surveys_questions_rels USING btree (survey_questions_id);
