-- Initial Payload CMS schema migration
-- Creates the payload schema and initial tables

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create enum types
CREATE TYPE payload.enum_documentation_status AS ENUM ('draft', 'published');

-- Create tables
CREATE TABLE IF NOT EXISTS payload.users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  email varchar NOT NULL,
  reset_password_token varchar,
  reset_password_expiration timestamp(3) with time zone,
  salt varchar,
  hash varchar,
  login_attempts numeric DEFAULT 0,
  lock_until timestamp(3) with time zone
);

CREATE TABLE IF NOT EXISTS payload.media (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  alt varchar NOT NULL,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  url varchar,
  thumbnail_u_r_l varchar,
  filename varchar,
  mime_type varchar,
  filesize numeric,
  width numeric,
  height numeric,
  focal_x numeric,
  focal_y numeric
);

CREATE TABLE IF NOT EXISTS payload.documentation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title varchar NOT NULL,
  slug varchar NOT NULL,
  description varchar,
  content jsonb NOT NULL,
  published_at timestamp(3) with time zone,
  status payload.enum_documentation_status DEFAULT 'draft' NOT NULL,
  "order" numeric DEFAULT 0,
  parent_id integer,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS payload.documentation_categories (
  _order integer NOT NULL,
  _parent_id integer NOT NULL,
  id varchar PRIMARY KEY NOT NULL,
  category varchar
);

CREATE TABLE IF NOT EXISTS payload.documentation_tags (
  _order integer NOT NULL,
  _parent_id integer NOT NULL,
  id varchar PRIMARY KEY NOT NULL,
  tag varchar
);

CREATE TABLE IF NOT EXISTS payload.payload_locked_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  global_slug varchar,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS payload.payload_locked_documents_rels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order" integer,
  parent_id integer NOT NULL,
  path varchar NOT NULL,
  users_id integer,
  media_id integer,
  documentation_id integer
);

CREATE TABLE IF NOT EXISTS payload.payload_preferences (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  key varchar,
  value jsonb,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS payload.payload_preferences_rels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order" integer,
  parent_id integer NOT NULL,
  path varchar NOT NULL,
  users_id integer
);

CREATE TABLE IF NOT EXISTS payload.payload_migrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  name varchar,
  batch numeric,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.documentation_categories ADD CONSTRAINT documentation_categories_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES payload.documentation(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.documentation_tags ADD CONSTRAINT documentation_tags_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES payload.documentation(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.documentation ADD CONSTRAINT documentation_parent_id_documentation_id_fk FOREIGN KEY (parent_id) REFERENCES payload.documentation(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.payload_locked_documents_rels ADD CONSTRAINT payload_locked_documents_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES payload.payload_locked_documents(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.payload_locked_documents_rels ADD CONSTRAINT payload_locked_documents_rels_users_fk FOREIGN KEY (users_id) REFERENCES payload.users(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.payload_locked_documents_rels ADD CONSTRAINT payload_locked_documents_rels_media_fk FOREIGN KEY (media_id) REFERENCES payload.media(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.payload_locked_documents_rels ADD CONSTRAINT payload_locked_documents_rels_documentation_fk FOREIGN KEY (documentation_id) REFERENCES payload.documentation(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.payload_preferences_rels ADD CONSTRAINT payload_preferences_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES payload.payload_preferences(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.payload_preferences_rels ADD CONSTRAINT payload_preferences_rels_users_fk FOREIGN KEY (users_id) REFERENCES payload.users(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS users_updated_at_idx ON payload.users USING btree (updated_at);
CREATE INDEX IF NOT EXISTS users_created_at_idx ON payload.users USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON payload.users USING btree (email);

CREATE INDEX IF NOT EXISTS media_updated_at_idx ON payload.media USING btree (updated_at);
CREATE INDEX IF NOT EXISTS media_created_at_idx ON payload.media USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS media_filename_idx ON payload.media USING btree (filename);

CREATE INDEX IF NOT EXISTS documentation_categories_order_idx ON payload.documentation_categories USING btree (_order);
CREATE INDEX IF NOT EXISTS documentation_categories_parent_id_idx ON payload.documentation_categories USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS documentation_tags_order_idx ON payload.documentation_tags USING btree (_order);
CREATE INDEX IF NOT EXISTS documentation_tags_parent_id_idx ON payload.documentation_tags USING btree (_parent_id);

CREATE INDEX IF NOT EXISTS documentation_parent_idx ON payload.documentation USING btree (parent_id);
CREATE INDEX IF NOT EXISTS documentation_updated_at_idx ON payload.documentation USING btree (updated_at);
CREATE INDEX IF NOT EXISTS documentation_created_at_idx ON payload.documentation USING btree (created_at);

CREATE INDEX IF NOT EXISTS payload_locked_documents_global_slug_idx ON payload.payload_locked_documents USING btree (global_slug);
CREATE INDEX IF NOT EXISTS payload_locked_documents_updated_at_idx ON payload.payload_locked_documents USING btree (updated_at);
CREATE INDEX IF NOT EXISTS payload_locked_documents_created_at_idx ON payload.payload_locked_documents USING btree (created_at);

CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_order_idx ON payload.payload_locked_documents_rels USING btree ("order");
CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_parent_idx ON payload.payload_locked_documents_rels USING btree (parent_id);
CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_path_idx ON payload.payload_locked_documents_rels USING btree (path);
CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_users_id_idx ON payload.payload_locked_documents_rels USING btree (users_id);
CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_media_id_idx ON payload.payload_locked_documents_rels USING btree (media_id);
CREATE INDEX IF NOT EXISTS payload_locked_documents_rels_documentation_id_idx ON payload.payload_locked_documents_rels USING btree (documentation_id);

CREATE INDEX IF NOT EXISTS payload_preferences_key_idx ON payload.payload_preferences USING btree (key);
CREATE INDEX IF NOT EXISTS payload_preferences_updated_at_idx ON payload.payload_preferences USING btree (updated_at);
CREATE INDEX IF NOT EXISTS payload_preferences_created_at_idx ON payload.payload_preferences USING btree (created_at);

CREATE INDEX IF NOT EXISTS payload_preferences_rels_order_idx ON payload.payload_preferences_rels USING btree ("order");
CREATE INDEX IF NOT EXISTS payload_preferences_rels_parent_idx ON payload.payload_preferences_rels USING btree (parent_id);
CREATE INDEX IF NOT EXISTS payload_preferences_rels_path_idx ON payload.payload_preferences_rels USING btree (path);
CREATE INDEX IF NOT EXISTS payload_preferences_rels_users_id_idx ON payload.payload_preferences_rels USING btree (users_id);

CREATE INDEX IF NOT EXISTS payload_migrations_updated_at_idx ON payload.payload_migrations USING btree (updated_at);
CREATE INDEX IF NOT EXISTS payload_migrations_created_at_idx ON payload.payload_migrations USING btree (created_at);
