-- Create survey_responses table for Payload CMS
-- This table is for user responses to surveys

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create the survey_responses table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.survey_responses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  user_id varchar NOT NULL,
  survey integer,
  responses jsonb,
  progress numeric DEFAULT 0,
  category_scores jsonb,
  highest_scoring_category varchar,
  lowest_scoring_category varchar,
  completed boolean DEFAULT false,
  created_at timestamp(3) with time zone,
  updated_at timestamp(3) with time zone,
  updated_at_system timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at_system timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.survey_responses ADD CONSTRAINT survey_responses_survey_fk FOREIGN KEY (survey) REFERENCES payload.surveys(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
  -- If the surveys table doesn't exist yet, we'll skip this constraint
  WHEN undefined_table THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS survey_responses_user_id_idx ON payload.survey_responses USING btree (user_id);
CREATE INDEX IF NOT EXISTS survey_responses_survey_idx ON payload.survey_responses USING btree (survey);
CREATE INDEX IF NOT EXISTS survey_responses_completed_idx ON payload.survey_responses USING btree (completed);
CREATE INDEX IF NOT EXISTS survey_responses_updated_at_system_idx ON payload.survey_responses USING btree (updated_at_system);
CREATE INDEX IF NOT EXISTS survey_responses_created_at_system_idx ON payload.survey_responses USING btree (created_at_system);
