-- Create survey_questions table for Payload CMS
-- This table is for questions in surveys

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create the survey_questions table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.survey_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  text varchar NOT NULL,
  type varchar DEFAULT 'multiple_choice',
  description varchar,
  required boolean DEFAULT true,
  category varchar NOT NULL,
  questionspin varchar DEFAULT 'Positive',
  position numeric DEFAULT 0,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Create the survey_questions_options table for the array field
CREATE TABLE IF NOT EXISTS payload.survey_questions_options (
  _order integer NOT NULL,
  _parent_id integer NOT NULL,
  id varchar PRIMARY KEY NOT NULL,
  option varchar NOT NULL
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.survey_questions_options ADD CONSTRAINT survey_questions_options_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES payload.survey_questions(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS survey_questions_updated_at_idx ON payload.survey_questions USING btree (updated_at);
CREATE INDEX IF NOT EXISTS survey_questions_created_at_idx ON payload.survey_questions USING btree (created_at);
CREATE INDEX IF NOT EXISTS survey_questions_options_order_idx ON payload.survey_questions_options USING btree (_order);
CREATE INDEX IF NOT EXISTS survey_questions_options_parent_id_idx ON payload.survey_questions_options USING btree (_parent_id);
