-- Consolidated migration file for fixing all Payload CMS relationship tables
-- This migration combines the following migrations:
-- - 20250325160200_fix_payload_quiz_questions.sql
-- - 20250325171200_payload_fix_courses_rels.sql
-- - 20250325171400_payload_fix_courses_lessons_rels.sql
-- - 20250325171600_payload_fix_courses_double_underscore.sql

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- =============================================
-- Fix quiz_questions table
-- =============================================

-- Check if the quiz_questions table exists and drop it if it does
DO $$ 
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'payload' AND table_name = 'quiz_questions') THEN
    DROP TABLE IF EXISTS "payload"."quiz_questions_options" CASCADE;
    DROP TABLE IF EXISTS "payload"."quiz_questions" CASCADE;
  END IF;
END $$;

-- Create the quiz_questions table with proper column names and types
CREATE TABLE IF NOT EXISTS "payload"."quiz_questions" (
  "id" varchar PRIMARY KEY NOT NULL,
  "question" varchar NOT NULL,
  "quiz" integer,
  "type" varchar DEFAULT 'multiple_choice',
  "explanation" varchar,
  "order" numeric DEFAULT 0,
  "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "payload"."quiz_questions_options" (
  "_order" integer NOT NULL,
  "_parent_id" varchar NOT NULL,
  "id" varchar PRIMARY KEY NOT NULL,
  "text" varchar NOT NULL,
  "is_correct" boolean DEFAULT false
);

DO $$ BEGIN
 ALTER TABLE "payload"."quiz_questions" ADD CONSTRAINT "quiz_questions_quiz_fk" FOREIGN KEY ("quiz") REFERENCES "payload"."course_quizzes"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "payload"."quiz_questions_options" ADD CONSTRAINT "quiz_questions_options_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "payload"."quiz_questions"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS "quiz_questions_quiz_idx" ON "payload"."quiz_questions" USING btree ("quiz");
CREATE INDEX IF NOT EXISTS "quiz_questions_updated_at_idx" ON "payload"."quiz_questions" USING btree ("updated_at");
CREATE INDEX IF NOT EXISTS "quiz_questions_created_at_idx" ON "payload"."quiz_questions" USING btree ("created_at");
CREATE INDEX IF NOT EXISTS "quiz_questions_options_order_idx" ON "payload"."quiz_questions_options" USING btree ("_order");
CREATE INDEX IF NOT EXISTS "quiz_questions_options_parent_id_idx" ON "payload"."quiz_questions_options" USING btree ("_parent_id");

-- =============================================
-- Create courses_rels table
-- =============================================

CREATE TABLE IF NOT EXISTS payload.courses_rels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order" integer,
  parent_id integer NOT NULL,
  path varchar NOT NULL,
  related_id integer,
  related_collection varchar
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.courses_rels ADD CONSTRAINT courses_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES payload.courses(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS courses_rels_order_idx ON payload.courses_rels USING btree ("order");
CREATE INDEX IF NOT EXISTS courses_rels_parent_idx ON payload.courses_rels USING btree (parent_id);
CREATE INDEX IF NOT EXISTS courses_rels_path_idx ON payload.courses_rels USING btree (path);
CREATE INDEX IF NOT EXISTS courses_rels_related_id_idx ON payload.courses_rels USING btree (related_id);
CREATE INDEX IF NOT EXISTS courses_rels_related_collection_idx ON payload.courses_rels USING btree (related_collection);

-- =============================================
-- Create courses_lessons_rels table
-- =============================================

CREATE TABLE IF NOT EXISTS payload.courses_lessons_rels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order" integer,
  parent_id integer NOT NULL,
  path varchar NOT NULL,
  course_lessons_id integer
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.courses_lessons_rels ADD CONSTRAINT courses_lessons_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES payload.courses(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.courses_lessons_rels ADD CONSTRAINT courses_lessons_rels_course_lessons_fk FOREIGN KEY (course_lessons_id) REFERENCES payload.course_lessons(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
  -- If the course_lessons table doesn't exist yet, we'll skip this constraint
  WHEN undefined_table THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS courses_lessons_rels_order_idx ON payload.courses_lessons_rels USING btree ("order");
CREATE INDEX IF NOT EXISTS courses_lessons_rels_parent_idx ON payload.courses_lessons_rels USING btree (parent_id);
CREATE INDEX IF NOT EXISTS courses_lessons_rels_path_idx ON payload.courses_lessons_rels USING btree (path);
CREATE INDEX IF NOT EXISTS courses_lessons_rels_course_lessons_id_idx ON payload.courses_lessons_rels USING btree (course_lessons_id);

-- =============================================
-- Fix courses__rels (double underscore) table
-- =============================================

-- Check if courses__rels exists, and if not, create it
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'payload' AND table_name = 'courses__rels') THEN
        -- Create courses__rels table based on courses_rels structure
        CREATE TABLE payload.courses__rels (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            "order" integer,
            parent_id integer NOT NULL,
            path varchar NOT NULL,
            course_lessons_id integer
        );

        -- Copy data from courses_rels if it exists
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'payload' AND table_name = 'courses_rels') THEN
            INSERT INTO payload.courses__rels (id, "order", parent_id, path, course_lessons_id)
            SELECT id, "order", parent_id, path, NULL
            FROM payload.courses_rels;
        END IF;

        -- Add foreign key constraints
        ALTER TABLE payload.courses__rels 
        ADD CONSTRAINT courses__rels_parent_fk 
        FOREIGN KEY (parent_id) REFERENCES payload.courses(id) ON DELETE cascade ON UPDATE no action;

        -- Create indexes
        CREATE INDEX IF NOT EXISTS courses__rels_order_idx ON payload.courses__rels USING btree ("order");
        CREATE INDEX IF NOT EXISTS courses__rels_parent_idx ON payload.courses__rels USING btree (parent_id);
        CREATE INDEX IF NOT EXISTS courses__rels_path_idx ON payload.courses__rels USING btree (path);
        CREATE INDEX IF NOT EXISTS courses__rels_course_lessons_id_idx ON payload.courses__rels USING btree (course_lessons_id);
    END IF;
END $$;
