packages:
  - apps/*
  - packages/**
  - tooling/*
  - .claude/scripts

catalog:
  '@types/node': 24.9.1
  '@types/react': 19.2.2

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - supabase
