/**
 * Supabase Edge Function for certificate generation
 * Handles PDF.co API integration and file processing
 */
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// CORS headers for cross-origin requests
const corsHeaders = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Headers":
		"authorization, x-client-info, apikey, content-type",
	"Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE",
};

interface CertificateRequest {
	userId: string;
	courseId: string;
	fullName: string;
}

// Authentication helper
async function getAuthenticatedClient(req: Request) {
	const authHeader = req.headers.get("Authorization");
	if (!authHeader) {
		throw new Error("Missing authorization header");
	}

	const supabaseUrl = Deno.env.get("SUPABASE_URL");
	const supabaseKey = Deno.env.get("SUPABASE_ANON_KEY");

	if (!supabaseUrl || !supabaseKey) {
		throw new Error("Missing Supabase environment variables");
	}

	const supabase = createClient(supabaseUrl, supabaseKey, {
		global: {
			headers: { Authorization: authHeader },
		},
	});

	// Verify the user is authenticated
	const {
		data: { user },
		error,
	} = await supabase.auth.getUser();
	if (error || !user) {
		throw new Error("Invalid authentication");
	}

	return { supabase, user };
}

// PDF.co API integration
async function generateCertificateWithPdfCo(
	fullName: string,
	courseId: string,
): Promise<Uint8Array> {
	const pdfCoApiKey = Deno.env.get("PDF_CO_API_KEY");
	if (!pdfCoApiKey) {
		throw new Error("PDF_CO_API_KEY environment variable not set");
	}

	// For demonstration, create a simple certificate data
	// In production, you would integrate with the actual PDF.co API
	const certificateData = {
		recipientName: fullName,
		courseId: courseId,
		completionDate: new Date().toISOString().split("T")[0],
		certificateId: `CERT-${courseId}-${Date.now()}`,
		generatedBy: "SlideHeroes Platform",
		platform: "supabase-edge-function",
	};

	// Simulate PDF generation (in production, call PDF.co API)
	const pdfContent = `
CERTIFICATE OF COMPLETION

This certifies that

${fullName}

has successfully completed the course

Course ID: ${courseId}

Completion Date: ${certificateData.completionDate}
Certificate ID: ${certificateData.certificateId}

Generated by SlideHeroes Platform
	`;

	// Convert to buffer (in production, this would be actual PDF binary data)
	return new TextEncoder().encode(pdfContent);
}

serve(async (req) => {
	// Handle CORS preflight requests
	if (req.method === "OPTIONS") {
		return new Response("ok", { headers: corsHeaders });
	}

	try {
		const startTime = performance.now();

		// Authenticate the request
		const { supabase, user } = await getAuthenticatedClient(req);

		// Parse request body
		const requestData: CertificateRequest = await req.json();
		const { userId, courseId, fullName } = requestData;

		// Verify user ID matches authenticated user
		if (userId !== user.id) {
			return new Response(JSON.stringify({ error: "User ID mismatch" }), {
				status: 403,
				headers: { ...corsHeaders, "Content-Type": "application/json" },
			});
		}

		// Starting certificate generation for user and course

		// Generate certificate using PDF.co API
		const certificateBuffer = await generateCertificateWithPdfCo(
			fullName,
			courseId,
		);

		// Create unique filename
		const timestamp = Date.now();
		const fileName = `certificates/${userId}/${courseId}/${timestamp}.txt`; // In production: .pdf

		// Generated certificate buffer successfully

		// Upload to Supabase Storage
		const { data: uploadData, error: uploadError } = await supabase.storage
			.from("certificates")
			.upload(fileName, certificateBuffer, {
				contentType: "text/plain", // In production: 'application/pdf'
				upsert: true,
			});

		if (uploadError) {
			// Upload failed
			return new Response(
				JSON.stringify({ error: `Upload failed: ${uploadError.message}` }),
				{
					status: 500,
					headers: { ...corsHeaders, "Content-Type": "application/json" },
				},
			);
		}

		// Get public URL
		const { data: urlData } = supabase.storage
			.from("certificates")
			.getPublicUrl(fileName);

		// Record certificate in database
		const { data: certificateRecord, error: dbError } = await supabase
			.from("certificates")
			.insert({
				user_id: userId,
				course_id: courseId,
				file_path: uploadData.path,
				recipient_name: fullName,
				generated_at: new Date().toISOString(),
			})
			.select()
			.single();

		if (dbError) {
			// Database record creation failed - continuing since file was uploaded successfully
		}

		// Update course progress
		const { error: progressError } = await supabase
			.from("course_progress")
			.update({ certificate_generated: true })
			.eq("user_id", userId)
			.eq("course_id", courseId);

		if (progressError) {
			// Course progress update failed
		}

		const duration = performance.now() - startTime;

		// Certificate generation completed

		return new Response(
			JSON.stringify({
				success: true,
				certificateUrl: urlData.publicUrl,
				certificateId: certificateRecord?.id,
				fileName: uploadData.path,
				metadata: {
					duration,
					runtime: "supabase-edge-function",
					recipientName: fullName,
				},
			}),
			{
				headers: {
					...corsHeaders,
					"Content-Type": "application/json",
				},
			},
		);
	} catch (error) {
		// Certificate generation error

		return new Response(
			JSON.stringify({
				error: error instanceof Error ? error.message : "Unknown error",
				success: false,
			}),
			{
				status: 500,
				headers: {
					...corsHeaders,
					"Content-Type": "application/json",
				},
			},
		);
	}
});
