-- Create course_quizzes table for Payload CMS
-- This table is referenced by the quiz_questions table

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create the course_quizzes table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.course_quizzes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title varchar NOT NULL,
  description varchar,
  passing_score numeric DEFAULT 70 NOT NULL,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS course_quizzes_updated_at_idx ON payload.course_quizzes USING btree (updated_at);
CREATE INDEX IF NOT EXISTS course_quizzes_created_at_idx ON payload.course_quizzes USING btree (created_at);
