-- Create courses table for Payload CMS
-- This table is referenced by the course_lessons table

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create enum types
CREATE TYPE payload.enum_courses_status AS ENUM ('draft', 'published');

-- Create the courses table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title varchar NOT NULL,
  slug varchar NOT NULL UNIQUE,
  description varchar,
  status payload.enum_courses_status DEFAULT 'draft' NOT NULL,
  intro_content jsonb,
  completion_content jsonb,
  estimated_duration numeric,
  show_progress_bar boolean DEFAULT true,
  published_at timestamp(3) with time zone,
  featured_image integer,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Create the courses_lessons_rels table for the many-to-many relationship
CREATE TABLE IF NOT EXISTS payload.courses_lessons_rels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "order" integer,
  parent_id integer NOT NULL,
  path varchar NOT NULL,
  course_lessons_id integer
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.courses ADD CONSTRAINT courses_featured_image_fk FOREIGN KEY (featured_image) REFERENCES payload.media(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.courses_lessons_rels ADD CONSTRAINT courses_lessons_rels_parent_fk FOREIGN KEY (parent_id) REFERENCES payload.courses(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.courses_lessons_rels ADD CONSTRAINT courses_lessons_rels_course_lessons_fk FOREIGN KEY (course_lessons_id) REFERENCES payload.course_lessons(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
  -- If the course_lessons table doesn't exist yet, we'll skip this constraint
  WHEN undefined_table THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS courses_featured_image_idx ON payload.courses USING btree (featured_image);
CREATE INDEX IF NOT EXISTS courses_updated_at_idx ON payload.courses USING btree (updated_at);
CREATE INDEX IF NOT EXISTS courses_created_at_idx ON payload.courses USING btree (created_at);
CREATE INDEX IF NOT EXISTS courses_lessons_rels_order_idx ON payload.courses_lessons_rels USING btree ("order");
CREATE INDEX IF NOT EXISTS courses_lessons_rels_parent_idx ON payload.courses_lessons_rels USING btree (parent_id);
CREATE INDEX IF NOT EXISTS courses_lessons_rels_path_idx ON payload.courses_lessons_rels USING btree (path);
CREATE INDEX IF NOT EXISTS courses_lessons_rels_course_lessons_id_idx ON payload.courses_lessons_rels USING btree (course_lessons_id);
