-- Create posts table for Payload CMS
-- This table is for blog posts on the website

-- First, ensure the payload schema exists
CREATE SCHEMA IF NOT EXISTS payload;

-- Create enum types
CREATE TYPE payload.enum_posts_status AS ENUM ('draft', 'published');

-- Create the posts table if it doesn't exist
CREATE TABLE IF NOT EXISTS payload.posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  title varchar NOT NULL,
  slug varchar NOT NULL UNIQUE,
  description varchar,
  content jsonb NOT NULL,
  published_at timestamp(3) with time zone DEFAULT now(),
  status payload.enum_posts_status DEFAULT 'draft' NOT NULL,
  image integer,
  updated_at timestamp(3) with time zone DEFAULT now() NOT NULL,
  created_at timestamp(3) with time zone DEFAULT now() NOT NULL
);

-- Create the posts_categories table for the array field
CREATE TABLE IF NOT EXISTS payload.posts_categories (
  _order integer NOT NULL,
  _parent_id integer NOT NULL,
  id varchar PRIMARY KEY NOT NULL,
  category varchar
);

-- Create the posts_tags table for the array field
CREATE TABLE IF NOT EXISTS payload.posts_tags (
  _order integer NOT NULL,
  _parent_id integer NOT NULL,
  id varchar PRIMARY KEY NOT NULL,
  tag varchar
);

-- Add foreign key constraints
DO $$ BEGIN
  ALTER TABLE payload.posts ADD CONSTRAINT posts_image_fk FOREIGN KEY (image) REFERENCES payload.media(id) ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.posts_categories ADD CONSTRAINT posts_categories_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES payload.posts(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER TABLE payload.posts_tags ADD CONSTRAINT posts_tags_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES payload.posts(id) ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS posts_image_idx ON payload.posts USING btree (image);
CREATE INDEX IF NOT EXISTS posts_updated_at_idx ON payload.posts USING btree (updated_at);
CREATE INDEX IF NOT EXISTS posts_created_at_idx ON payload.posts USING btree (created_at);
CREATE INDEX IF NOT EXISTS posts_categories_order_idx ON payload.posts_categories USING btree (_order);
CREATE INDEX IF NOT EXISTS posts_categories_parent_id_idx ON payload.posts_categories USING btree (_parent_id);
CREATE INDEX IF NOT EXISTS posts_tags_order_idx ON payload.posts_tags USING btree (_order);
CREATE INDEX IF NOT EXISTS posts_tags_parent_id_idx ON payload.posts_tags USING btree (_parent_id);
