/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgSchema,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  timestamp,
  varchar,
  numeric,
  integer,
  jsonb,
  type AnyPgColumn,
  boolean,
  serial,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const db_schema = pgSchema('payload')
export const enum_documentation_status = db_schema.enum('enum_documentation_status', [
  'draft',
  'published',
])
export const enum_posts_status = db_schema.enum('enum_posts_status', ['draft', 'published'])
export const enum_surveys_status = db_schema.enum('enum_surveys_status', ['draft', 'published'])
export const enum_survey_questions_type = db_schema.enum('enum_survey_questions_type', [
  'multiple_choice',
])
export const enum_survey_questions_questionspin = db_schema.enum(
  'enum_survey_questions_questionspin',
  ['Positive', 'Negative'],
)
export const enum_courses_status = db_schema.enum('enum_courses_status', ['draft', 'published'])
export const enum_quiz_questions_type = db_schema.enum('enum_quiz_questions_type', [
  'multiple_choice',
])

export const users = db_schema.table(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const media = db_schema.table(
  'media',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const documentation_categories = db_schema.table(
  'documentation_categories',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    category: varchar('category'),
  },
  (columns) => ({
    _orderIdx: index('documentation_categories_order_idx').on(columns._order),
    _parentIDIdx: index('documentation_categories_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [documentation.id],
      name: 'documentation_categories_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const documentation_tags = db_schema.table(
  'documentation_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag'),
  },
  (columns) => ({
    _orderIdx: index('documentation_tags_order_idx').on(columns._order),
    _parentIDIdx: index('documentation_tags_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [documentation.id],
      name: 'documentation_tags_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const documentation_breadcrumbs = db_schema.table(
  'documentation_breadcrumbs',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    doc: uuid('doc_id').references(() => documentation.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    label: varchar('label'),
  },
  (columns) => ({
    _orderIdx: index('documentation_breadcrumbs_order_idx').on(columns._order),
    _parentIDIdx: index('documentation_breadcrumbs_parent_id_idx').on(columns._parentID),
    documentation_breadcrumbs_doc_idx: index('documentation_breadcrumbs_doc_idx').on(columns.doc),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [documentation.id],
      name: 'documentation_breadcrumbs_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const documentation = db_schema.table(
  'documentation',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    content: jsonb('content'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    status: enum_documentation_status('status').notNull().default('draft'),
    order: numeric('order').default('0'),
    parent: uuid('parent_id').references((): AnyPgColumn => documentation.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    documentation_parent_idx: index('documentation_parent_idx').on(columns.parent),
    documentation_updated_at_idx: index('documentation_updated_at_idx').on(columns.updatedAt),
    documentation_created_at_idx: index('documentation_created_at_idx').on(columns.createdAt),
  }),
)

export const posts_categories = db_schema.table(
  'posts_categories',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    category: varchar('category'),
  },
  (columns) => ({
    _orderIdx: index('posts_categories_order_idx').on(columns._order),
    _parentIDIdx: index('posts_categories_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_categories_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const posts_tags = db_schema.table(
  'posts_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag'),
  },
  (columns) => ({
    _orderIdx: index('posts_tags_order_idx').on(columns._order),
    _parentIDIdx: index('posts_tags_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_tags_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const posts = db_schema.table(
  'posts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    content: jsonb('content').notNull(),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    image_id: uuid('image_id_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status: enum_posts_status('status').notNull().default('draft'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    posts_image_id_idx: index('posts_image_id_idx').on(columns.image_id),
    posts_updated_at_idx: index('posts_updated_at_idx').on(columns.updatedAt),
    posts_created_at_idx: index('posts_created_at_idx').on(columns.createdAt),
  }),
)

export const surveys = db_schema.table(
  'surveys',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    startMessage: jsonb('start_message'),
    endMessage: jsonb('end_message'),
    showProgressBar: boolean('show_progress_bar').default(true),
    summaryContent: jsonb('summary_content'),
    status: enum_surveys_status('status').notNull().default('draft'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    surveys_slug_idx: uniqueIndex('surveys_slug_idx').on(columns.slug),
    surveys_updated_at_idx: index('surveys_updated_at_idx').on(columns.updatedAt),
    surveys_created_at_idx: index('surveys_created_at_idx').on(columns.createdAt),
  }),
)

export const surveys_rels = db_schema.table(
  'surveys_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    survey_questionsID: uuid('survey_questions_id'),
  },
  (columns) => ({
    order: index('surveys_rels_order_idx').on(columns.order),
    parentIdx: index('surveys_rels_parent_idx').on(columns.parent),
    pathIdx: index('surveys_rels_path_idx').on(columns.path),
    surveys_rels_survey_questions_id_idx: index('surveys_rels_survey_questions_id_idx').on(
      columns.survey_questionsID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [surveys.id],
      name: 'surveys_rels_parent_fk',
    }).onDelete('cascade'),
    survey_questionsIdFk: foreignKey({
      columns: [columns['survey_questionsID']],
      foreignColumns: [survey_questions.id],
      name: 'surveys_rels_survey_questions_fk',
    }).onDelete('cascade'),
  }),
)

export const survey_questions_options = db_schema.table(
  'survey_questions_options',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    option: varchar('option').notNull(),
  },
  (columns) => ({
    _orderIdx: index('survey_questions_options_order_idx').on(columns._order),
    _parentIDIdx: index('survey_questions_options_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [survey_questions.id],
      name: 'survey_questions_options_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const survey_questions = db_schema.table(
  'survey_questions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    text: varchar('text').notNull(),
    type: enum_survey_questions_type('type').notNull().default('multiple_choice'),
    description: varchar('description'),
    required: boolean('required').default(true),
    category: varchar('category').notNull(),
    questionspin: enum_survey_questions_questionspin('questionspin').notNull().default('Positive'),
    position: numeric('position').default('0'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    survey_questions_updated_at_idx: index('survey_questions_updated_at_idx').on(columns.updatedAt),
    survey_questions_created_at_idx: index('survey_questions_created_at_idx').on(columns.createdAt),
  }),
)

export const courses = db_schema.table(
  'courses',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    status: enum_courses_status('status').notNull().default('draft'),
    featured_image_id: uuid('featured_image_id_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    introContent: jsonb('intro_content'),
    completionContent: jsonb('completion_content'),
    estimatedDuration: numeric('estimated_duration'),
    showProgressBar: boolean('show_progress_bar').default(true),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    courses_slug_idx: uniqueIndex('courses_slug_idx').on(columns.slug),
    courses_featured_image_id_idx: index('courses_featured_image_id_idx').on(
      columns.featured_image_id,
    ),
    courses_updated_at_idx: index('courses_updated_at_idx').on(columns.updatedAt),
    courses_created_at_idx: index('courses_created_at_idx').on(columns.createdAt),
  }),
)

export const courses_rels = db_schema.table(
  'courses_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    course_lessonsID: uuid('course_lessons_id'),
  },
  (columns) => ({
    order: index('courses_rels_order_idx').on(columns.order),
    parentIdx: index('courses_rels_parent_idx').on(columns.parent),
    pathIdx: index('courses_rels_path_idx').on(columns.path),
    courses_rels_course_lessons_id_idx: index('courses_rels_course_lessons_id_idx').on(
      columns.course_lessonsID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [courses.id],
      name: 'courses_rels_parent_fk',
    }).onDelete('cascade'),
    course_lessonsIdFk: foreignKey({
      columns: [columns['course_lessonsID']],
      foreignColumns: [course_lessons.id],
      name: 'courses_rels_course_lessons_fk',
    }).onDelete('cascade'),
  }),
)

export const course_lessons = db_schema.table(
  'course_lessons',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    featured_image_id: uuid('featured_image_id_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    content: jsonb('content'),
    lessonNumber: numeric('lesson_number').notNull(),
    estimatedDuration: numeric('estimated_duration'),
    course_id: uuid('course_id_id')
      .notNull()
      .references(() => courses.id, {
        onDelete: 'set null',
      }),
    quiz_id: uuid('quiz_id_id').references(() => course_quizzes.id, {
      onDelete: 'set null',
    }),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    course_lessons_slug_idx: uniqueIndex('course_lessons_slug_idx').on(columns.slug),
    course_lessons_featured_image_id_idx: index('course_lessons_featured_image_id_idx').on(
      columns.featured_image_id,
    ),
    course_lessons_course_id_idx: index('course_lessons_course_id_idx').on(columns.course_id),
    course_lessons_quiz_id_idx: index('course_lessons_quiz_id_idx').on(columns.quiz_id),
    course_lessons_updated_at_idx: index('course_lessons_updated_at_idx').on(columns.updatedAt),
    course_lessons_created_at_idx: index('course_lessons_created_at_idx').on(columns.createdAt),
  }),
)

export const course_quizzes = db_schema.table(
  'course_quizzes',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description'),
    passingScore: numeric('passing_score').notNull().default('70'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    course_quizzes_updated_at_idx: index('course_quizzes_updated_at_idx').on(columns.updatedAt),
    course_quizzes_created_at_idx: index('course_quizzes_created_at_idx').on(columns.createdAt),
  }),
)

export const quiz_questions_options = db_schema.table(
  'quiz_questions_options',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    text: varchar('text').notNull(),
    isCorrect: boolean('is_correct').default(false),
  },
  (columns) => ({
    _orderIdx: index('quiz_questions_options_order_idx').on(columns._order),
    _parentIDIdx: index('quiz_questions_options_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [quiz_questions.id],
      name: 'quiz_questions_options_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const quiz_questions = db_schema.table(
  'quiz_questions',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    question: varchar('question').notNull(),
    quiz_id: uuid('quiz_id_id')
      .notNull()
      .references(() => course_quizzes.id, {
        onDelete: 'set null',
      }),
    type: enum_quiz_questions_type('type').notNull().default('multiple_choice'),
    explanation: varchar('explanation'),
    order: numeric('order').default('0'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    quiz_questions_quiz_id_idx: index('quiz_questions_quiz_id_idx').on(columns.quiz_id),
    quiz_questions_updated_at_idx: index('quiz_questions_updated_at_idx').on(columns.updatedAt),
    quiz_questions_created_at_idx: index('quiz_questions_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_locked_documents = db_schema.table(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = db_schema.table(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
    mediaID: uuid('media_id'),
    documentationID: uuid('documentation_id'),
    postsID: uuid('posts_id'),
    surveysID: uuid('surveys_id'),
    survey_questionsID: uuid('survey_questions_id'),
    coursesID: uuid('courses_id'),
    course_lessonsID: uuid('course_lessons_id'),
    course_quizzesID: uuid('course_quizzes_id'),
    quiz_questionsID: uuid('quiz_questions_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_documentation_id_idx: index(
      'payload_locked_documents_rels_documentation_id_idx',
    ).on(columns.documentationID),
    payload_locked_documents_rels_posts_id_idx: index(
      'payload_locked_documents_rels_posts_id_idx',
    ).on(columns.postsID),
    payload_locked_documents_rels_surveys_id_idx: index(
      'payload_locked_documents_rels_surveys_id_idx',
    ).on(columns.surveysID),
    payload_locked_documents_rels_survey_questions_id_idx: index(
      'payload_locked_documents_rels_survey_questions_id_idx',
    ).on(columns.survey_questionsID),
    payload_locked_documents_rels_courses_id_idx: index(
      'payload_locked_documents_rels_courses_id_idx',
    ).on(columns.coursesID),
    payload_locked_documents_rels_course_lessons_id_idx: index(
      'payload_locked_documents_rels_course_lessons_id_idx',
    ).on(columns.course_lessonsID),
    payload_locked_documents_rels_course_quizzes_id_idx: index(
      'payload_locked_documents_rels_course_quizzes_id_idx',
    ).on(columns.course_quizzesID),
    payload_locked_documents_rels_quiz_questions_id_idx: index(
      'payload_locked_documents_rels_quiz_questions_id_idx',
    ).on(columns.quiz_questionsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    documentationIdFk: foreignKey({
      columns: [columns['documentationID']],
      foreignColumns: [documentation.id],
      name: 'payload_locked_documents_rels_documentation_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    surveysIdFk: foreignKey({
      columns: [columns['surveysID']],
      foreignColumns: [surveys.id],
      name: 'payload_locked_documents_rels_surveys_fk',
    }).onDelete('cascade'),
    survey_questionsIdFk: foreignKey({
      columns: [columns['survey_questionsID']],
      foreignColumns: [survey_questions.id],
      name: 'payload_locked_documents_rels_survey_questions_fk',
    }).onDelete('cascade'),
    coursesIdFk: foreignKey({
      columns: [columns['coursesID']],
      foreignColumns: [courses.id],
      name: 'payload_locked_documents_rels_courses_fk',
    }).onDelete('cascade'),
    course_lessonsIdFk: foreignKey({
      columns: [columns['course_lessonsID']],
      foreignColumns: [course_lessons.id],
      name: 'payload_locked_documents_rels_course_lessons_fk',
    }).onDelete('cascade'),
    course_quizzesIdFk: foreignKey({
      columns: [columns['course_quizzesID']],
      foreignColumns: [course_quizzes.id],
      name: 'payload_locked_documents_rels_course_quizzes_fk',
    }).onDelete('cascade'),
    quiz_questionsIdFk: foreignKey({
      columns: [columns['quiz_questionsID']],
      foreignColumns: [quiz_questions.id],
      name: 'payload_locked_documents_rels_quiz_questions_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = db_schema.table(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = db_schema.table(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = db_schema.table(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_users = relations(users, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_documentation_categories = relations(
  documentation_categories,
  ({ one }) => ({
    _parentID: one(documentation, {
      fields: [documentation_categories._parentID],
      references: [documentation.id],
      relationName: 'categories',
    }),
  }),
)
export const relations_documentation_tags = relations(documentation_tags, ({ one }) => ({
  _parentID: one(documentation, {
    fields: [documentation_tags._parentID],
    references: [documentation.id],
    relationName: 'tags',
  }),
}))
export const relations_documentation_breadcrumbs = relations(
  documentation_breadcrumbs,
  ({ one }) => ({
    _parentID: one(documentation, {
      fields: [documentation_breadcrumbs._parentID],
      references: [documentation.id],
      relationName: 'breadcrumbs',
    }),
    doc: one(documentation, {
      fields: [documentation_breadcrumbs.doc],
      references: [documentation.id],
      relationName: 'doc',
    }),
  }),
)
export const relations_documentation = relations(documentation, ({ one, many }) => ({
  categories: many(documentation_categories, {
    relationName: 'categories',
  }),
  tags: many(documentation_tags, {
    relationName: 'tags',
  }),
  parent: one(documentation, {
    fields: [documentation.parent],
    references: [documentation.id],
    relationName: 'parent',
  }),
  breadcrumbs: many(documentation_breadcrumbs, {
    relationName: 'breadcrumbs',
  }),
}))
export const relations_posts_categories = relations(posts_categories, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_categories._parentID],
    references: [posts.id],
    relationName: 'categories',
  }),
}))
export const relations_posts_tags = relations(posts_tags, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_tags._parentID],
    references: [posts.id],
    relationName: 'tags',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  image_id: one(media, {
    fields: [posts.image_id],
    references: [media.id],
    relationName: 'image_id',
  }),
  categories: many(posts_categories, {
    relationName: 'categories',
  }),
  tags: many(posts_tags, {
    relationName: 'tags',
  }),
}))
export const relations_surveys_rels = relations(surveys_rels, ({ one }) => ({
  parent: one(surveys, {
    fields: [surveys_rels.parent],
    references: [surveys.id],
    relationName: '_rels',
  }),
  survey_questionsID: one(survey_questions, {
    fields: [surveys_rels.survey_questionsID],
    references: [survey_questions.id],
    relationName: 'survey_questions',
  }),
}))
export const relations_surveys = relations(surveys, ({ many }) => ({
  _rels: many(surveys_rels, {
    relationName: '_rels',
  }),
}))
export const relations_survey_questions_options = relations(
  survey_questions_options,
  ({ one }) => ({
    _parentID: one(survey_questions, {
      fields: [survey_questions_options._parentID],
      references: [survey_questions.id],
      relationName: 'options',
    }),
  }),
)
export const relations_survey_questions = relations(survey_questions, ({ many }) => ({
  options: many(survey_questions_options, {
    relationName: 'options',
  }),
}))
export const relations_courses_rels = relations(courses_rels, ({ one }) => ({
  parent: one(courses, {
    fields: [courses_rels.parent],
    references: [courses.id],
    relationName: '_rels',
  }),
  course_lessonsID: one(course_lessons, {
    fields: [courses_rels.course_lessonsID],
    references: [course_lessons.id],
    relationName: 'course_lessons',
  }),
}))
export const relations_courses = relations(courses, ({ one, many }) => ({
  featured_image_id: one(media, {
    fields: [courses.featured_image_id],
    references: [media.id],
    relationName: 'featured_image_id',
  }),
  _rels: many(courses_rels, {
    relationName: '_rels',
  }),
}))
export const relations_course_lessons = relations(course_lessons, ({ one }) => ({
  featured_image_id: one(media, {
    fields: [course_lessons.featured_image_id],
    references: [media.id],
    relationName: 'featured_image_id',
  }),
  course_id: one(courses, {
    fields: [course_lessons.course_id],
    references: [courses.id],
    relationName: 'course_id',
  }),
  quiz_id: one(course_quizzes, {
    fields: [course_lessons.quiz_id],
    references: [course_quizzes.id],
    relationName: 'quiz_id',
  }),
}))
export const relations_course_quizzes = relations(course_quizzes, () => ({}))
export const relations_quiz_questions_options = relations(quiz_questions_options, ({ one }) => ({
  _parentID: one(quiz_questions, {
    fields: [quiz_questions_options._parentID],
    references: [quiz_questions.id],
    relationName: 'options',
  }),
}))
export const relations_quiz_questions = relations(quiz_questions, ({ one, many }) => ({
  quiz_id: one(course_quizzes, {
    fields: [quiz_questions.quiz_id],
    references: [course_quizzes.id],
    relationName: 'quiz_id',
  }),
  options: many(quiz_questions_options, {
    relationName: 'options',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    documentationID: one(documentation, {
      fields: [payload_locked_documents_rels.documentationID],
      references: [documentation.id],
      relationName: 'documentation',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    surveysID: one(surveys, {
      fields: [payload_locked_documents_rels.surveysID],
      references: [surveys.id],
      relationName: 'surveys',
    }),
    survey_questionsID: one(survey_questions, {
      fields: [payload_locked_documents_rels.survey_questionsID],
      references: [survey_questions.id],
      relationName: 'survey_questions',
    }),
    coursesID: one(courses, {
      fields: [payload_locked_documents_rels.coursesID],
      references: [courses.id],
      relationName: 'courses',
    }),
    course_lessonsID: one(course_lessons, {
      fields: [payload_locked_documents_rels.course_lessonsID],
      references: [course_lessons.id],
      relationName: 'course_lessons',
    }),
    course_quizzesID: one(course_quizzes, {
      fields: [payload_locked_documents_rels.course_quizzesID],
      references: [course_quizzes.id],
      relationName: 'course_quizzes',
    }),
    quiz_questionsID: one(quiz_questions, {
      fields: [payload_locked_documents_rels.quiz_questionsID],
      references: [quiz_questions.id],
      relationName: 'quiz_questions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  db_schema: typeof db_schema
  enum_documentation_status: typeof enum_documentation_status
  enum_posts_status: typeof enum_posts_status
  enum_surveys_status: typeof enum_surveys_status
  enum_survey_questions_type: typeof enum_survey_questions_type
  enum_survey_questions_questionspin: typeof enum_survey_questions_questionspin
  enum_courses_status: typeof enum_courses_status
  enum_quiz_questions_type: typeof enum_quiz_questions_type
  users: typeof users
  media: typeof media
  documentation_categories: typeof documentation_categories
  documentation_tags: typeof documentation_tags
  documentation_breadcrumbs: typeof documentation_breadcrumbs
  documentation: typeof documentation
  posts_categories: typeof posts_categories
  posts_tags: typeof posts_tags
  posts: typeof posts
  surveys: typeof surveys
  surveys_rels: typeof surveys_rels
  survey_questions_options: typeof survey_questions_options
  survey_questions: typeof survey_questions
  courses: typeof courses
  courses_rels: typeof courses_rels
  course_lessons: typeof course_lessons
  course_quizzes: typeof course_quizzes
  quiz_questions_options: typeof quiz_questions_options
  quiz_questions: typeof quiz_questions
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_documentation_categories: typeof relations_documentation_categories
  relations_documentation_tags: typeof relations_documentation_tags
  relations_documentation_breadcrumbs: typeof relations_documentation_breadcrumbs
  relations_documentation: typeof relations_documentation
  relations_posts_categories: typeof relations_posts_categories
  relations_posts_tags: typeof relations_posts_tags
  relations_posts: typeof relations_posts
  relations_surveys_rels: typeof relations_surveys_rels
  relations_surveys: typeof relations_surveys
  relations_survey_questions_options: typeof relations_survey_questions_options
  relations_survey_questions: typeof relations_survey_questions
  relations_courses_rels: typeof relations_courses_rels
  relations_courses: typeof relations_courses
  relations_course_lessons: typeof relations_course_lessons
  relations_course_quizzes: typeof relations_course_quizzes
  relations_quiz_questions_options: typeof relations_quiz_questions_options
  relations_quiz_questions: typeof relations_quiz_questions
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres/types' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
